#!/bin/bash

PDFFILE="PDFOutput"
TEXFILE="Template"
PNGFILE="PNGOutput"
EXITCODE=0

if [[ $# -gt 1 ]]; then
    CUSTOMIZE=YES
fi

while [[ $# -gt 1 ]]; do
    KEY="$1"

    case $KEY in
        -l|--line)
            LINE="$2"
            shift
            ;;
        -b|--border)
            BORDER="$2"
            shift
            ;;
        -g|--background)
            BACKGROUND="$2"
            shift
            ;;
        -d|--displaystyle)
            DISPLAYSTYLE="$2"
            shift
            ;;
        -i|--input)
            INPUTPATH="$2"
            shift
            ;;
        -o|--output)
            OUTPUTPATH="$2"
            shift
            ;;
        --default)
            DEFAULT=YES
            ;;
        *)

            ;;
    esac
    shift
done

if [[ $CUSTOMIZE = YES ]]; then
    cat $TEXFILE.tex > tmp.tex
    TEXFILE=tmp
fi
if [[ -n $LINE ]]; then
    sed -ie '/[\\\]begin{document}/,/[\\\]end{document}/d' $TEXFILE.tex
    echo $"\\begin{document}$LINE\\end{document}" >> tmp.tex
fi
if [[ -n $BORDER ]]; then
    sed -ie "s/border=10pt/border=$BORDER/g" $TEXFILE.tex
    echo "[INFO]Change border length to $BORDER."
fi
if [[ -n $INPUTPATH ]]; then
    cat $INPUTPATH > $TEXFILE.tex
else
    EXITCODE=$?
    echo "[WARNING]The input file does not exist."
    exit $EXITCODE
fi
if [[ -f $TEXFILE.tex ]]; then
    if pdflatex $TEXFILE.tex && mv $TEXFILE.pdf $PDFFILE.pdf; then
        REMOVE=YES
        echo "[INFO]PDF file generated."
    else
        EXITCODE=$?
        echo "[WARNING]Error occurs when compiling the TeX file into PDF file."
        exit $EXITCODE
    fi
else
    EXITCODE=$?
    echo "[WARNING]The TeX file $TEXFILE.tex does not exist."
    exit $EXITCODE
fi
if [[ $REMOVE = YES ]]; then
    if [[ ( -f $TEXFILE.aux ) && ( -f $TEXFILE.log ) ]]; then
        if rm $TEXFILE.aux $TEXFILE.log; then
            echo "[INFO].aux and .log files removed."
        else
            EXITCODE=$?
            echo "[WARNING]Cannot remove .aux and .log files."
            exit $EXITCODE
        fi
    else
        EXITCODE=$?
        echo "[WARNING].aux and .log files do not exist and therefore cannot be removed."
        exit $EXITCODE
    fi
    if [[ -f $TEXFILE.texe ]]; then
        rm $TEXFILE.texe
        echo "[INFO].texe file removed."
    fi
fi
if [[ -f $PDFFILE.pdf ]]; then
    echo "[INFO]Generating PNG image from PDF file."
    if [[ ( -n $BACKGROUND ) && ( $BACKGROUND = "none" ) ]]; then
        if convert -density 800 $PDFFILE.pdf -quality 800 $PNGFILE.png; then
            echo "[INFO]PNG image without background successfully generated!"
        else
            EXITCODE=$?
            echo "[WARNING]Failed to generate PNG image without background."
            exit $EXITCODE
        fi
    elif convert -density 800 $PDFFILE.pdf -quality 800 -background white -alpha remove $PNGFILE.png; then
        echo "[INFO]PNG image successfully generated!"
    else
        EXITCODE=$?
        echo "[WARNING]Failed to generate PNG image."
        exit $EXITCODE
    fi
else
    EXITCODE=$?
    echo "[WARNING]The PDF file $PDFFILE.pdf does not exist."
    exit $EXITCODE
fi
if [[ -n $OUTPUTPATH ]]; then
    mv $PNGFILE.png $OUTPUTPATH
    echo "[INFO]The image file has been produced in the directory $OUTPUTPATH"
fi
if [[ $CUSTOMIZE = YES ]]; then
    rm $TEXFILE.tex
fi
